org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.caching=true
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2g
android.useAndroidX=true
android.nonTransitiveRClass=true
# AGP 9 与 Kotlin Multiplatform 兼容性 bypass（songci 已验证）
android.builtInKotlin=false
android.newDsl=false

# ---- 发布坐标 ----
# Maven Central 命名空间规则：io.github.<GitHub 用户名小写>
kheti.group=io.github.iamkings
kheti.version=0.1.0
