#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# 机密写入 Gradle 的用户级配置（仓库外，不会被提交）。
# gradle.properties 本身就是 KEY=VALUE 格式，因此可直接用 write_env 幂等 upsert；
# 已有的其它行（如 org.gradle.java.home）会被保留。
ENV_FILE="$HOME/.gradle/gradle.properties"
KEY_FILE="$HOME/.gradle/kheti-signing-key.asc"
GROUP_ID="io.github.iamkings"

banner "kheti → Maven Central 发布凭据"

# ── Stage 1 — GnuPG ───────────────────────────────────────────────────────
stage "安装 GnuPG"
if command -v gpg >/dev/null 2>&1; then
  say "已安装：$(gpg --version | head -1)"
else
  warn "本机没有 gpg"
  say "GnuPG 是签名构件的必需品（Maven Central 强制要求）。"
  if command -v brew >/dev/null 2>&1; then
    if confirm "用 Homebrew 安装 gnupg？"; then
      brew install gnupg
      say "已安装：$(gpg --version | head -1)"
    else
      warn "已取消。请手动安装 gnupg 后重新运行本脚本。"; exit 1
    fi
  else
    warn "也没找到 brew。请从 https://gnupg.org/download/ 手动安装后重新运行。"; exit 1
  fi
fi

# ── Stage 2 — 生成密钥对 ──────────────────────────────────────────────────
stage "生成 GPG 密钥对"
say "Maven Central 要求所有构件都有 PGP 签名，所以你需要一对自己的密钥。"
note ""
warn "务必选 RSA（默认的 ECC/ed25519 会生成“签名子密钥”，"
warn "而 Nexus 只能用主密钥验签 —— 这会让你发布时报验签失败）。"
note ""
say "接下来会进入 gpg 的交互式向导，请依次输入："
step "Kind of key：选 (1) RSA and RSA（默认第一项即可）"
step "Key size：输入 4096"
step "Expiry：按需，例如 2y（两年）；过期可以再延长"
step "Real name / Email：填会被公开看到的署名与邮箱"
step "Passphrase：设一个强口令 —— 签名时要用，务必记牢"
note ""
pause "按 Enter 启动 gpg 交互向导…"

if gpg --list-secret-keys --with-colons 2>/dev/null | grep -q '^sec:'; then
  note ""
  warn "检测到本机已有密钥。"
  EXISTING_KEY=$(gpg --list-secret-keys --keyid-format=long --with-colons | awk -F: '/^sec:/{print $5; exit}')
  note "现有主密钥：$EXISTING_KEY"
  if confirm "复用这个已有密钥（不生成新的）？"; then
    KEY_ID="$EXISTING_KEY"
    say "复用 $KEY_ID"
  else
    gpg --full-generate-key
    KEY_ID=$(gpg --list-secret-keys --keyid-format=long --with-colons | awk -F: '/^sec:/{print $5; exit}')
  fi
else
  gpg --full-generate-key
  KEY_ID=$(gpg --list-secret-keys --keyid-format=long --with-colons | awk -F: '/^sec:/{print $5; exit}')
fi

[[ -n "${KEY_ID:-}" ]] || { warn "没能识别出密钥 ID，请手动检查 gpg --list-secret-keys"; exit 1; }
say "主密钥 ID：$KEY_ID"

# 官方文档专门警告过签名子密钥的问题（Nexus 只认主密钥）
SIGNING_SUBKEYS=$(gpg --list-secret-keys --with-colons "$KEY_ID" 2>/dev/null | awk -F: '/^ssb:/ && $12 ~ /s/ {print $5}')
if [[ -n "$SIGNING_SUBKEYS" ]]; then
  note ""
  warn "该密钥带有签名子密钥：$SIGNING_SUBKEYS"
  warn "GPG 会用它签名，而 Maven Central 只能用主密钥验签，会导致发布失败。"
  say "处理办法（官方文档 “Delete a Sub Key”）："
  step "gpg --edit-key $KEY_ID"
  step "key <子密钥序号> → delkey（已发布过公钥则用 revkey）→ save"
  pause "处理完后按 Enter 继续…"
fi

# ── Stage 3 — 发布公钥 ────────────────────────────────────────────────────
stage "发布公钥到 keyserver"
say "别人（和 Maven Central）需要能查到你的公钥才能验签。"
note "官方支持的 keyserver：keyserver.ubuntu.com / keys.openpgp.org / pgp.mit.edu"
note ""
if gpg --keyserver keyserver.ubuntu.com --send-keys "$KEY_ID"; then
  say "已发送公钥 $KEY_ID"
else
  warn "发送失败（常见于网络/防火墙）。稍后手动重试："
  step "gpg --keyserver keyserver.ubuntu.com --send-keys $KEY_ID"
  step "或换一个：gpg --keyserver pgp.mit.edu --send-keys $KEY_ID"
  pause "按 Enter 继续…"
fi
note "提示：keys.openpgp.org 需要先完成邮箱验证，UID 才会公开，故这里以 ubuntu 为主。"

# ── Stage 4 — Portal Token ────────────────────────────────────────────────
stage "生成 Portal Token"
say "Portal Token 是你上传构件的凭据（用户名 + 密码一对）。"
open_url "https://central.sonatype.com/usertoken"
step "登录后点 “Generate User Token”"
step "填一个显示名（例如 kheti-release）和有效期"
step "弹窗里会同时给出 Username 与 Password，两个都要复制"
note ""
warn "弹窗一旦关闭就无法再次查看 —— 现在就要把两个值都复制出来。"
note ""
ask SONATYPE_USERNAME "粘贴 token 的 Username："
ask_secret SONATYPE_PASSWORD "粘贴 token 的 Password（输入不可见）："

# ── Stage 5 — 导出私钥 ────────────────────────────────────────────────────
stage "导出私钥到本地文件"
say "发布时 Gradle 需要读私钥来签名。导出为 ASCII 文件并收紧权限。"
note "gpg 可能会要求你输入私钥口令，按提示输入即可。"
note ""
if gpg --armor --export-secret-keys "$KEY_ID" > "$KEY_FILE" 2>/dev/null && [[ -s "$KEY_FILE" ]]; then
  chmod 600 "$KEY_FILE"
  say "已导出：$KEY_FILE（权限 600）"
else
  warn "导出失败。请手动执行："
  step "gpg --armor --export-secret-keys $KEY_ID > $KEY_FILE && chmod 600 $KEY_FILE"
  pause "完成后按 Enter 继续…"
fi
ask_secret SIGNING_PASSWORD "输入私钥口令（生成密钥时设的 passphrase）："

# ── Stage 6 — 写入配置并自检 ──────────────────────────────────────────────
stage "写入 Gradle 配置并自检"
say "把这四项写进 $ENV_FILE（仓库外，不会提交）："
write_env sonatype.username "$SONATYPE_USERNAME"
write_env sonatype.password "$SONATYPE_PASSWORD"
write_env signing.keyFile "$KEY_FILE"
write_env signing.password "$SIGNING_PASSWORD"
chmod 600 "$ENV_FILE" 2>/dev/null || true
note ""
say "自检："
MISSING=0
for k in sonatype.username sonatype.password signing.keyFile signing.password; do
  if grep -qE "^${k}=" "$ENV_FILE"; then
    note "  ✓ $k 已写入"
  else
    warn "  ✗ $k 缺失"; MISSING=1
  fi
done
if [[ -f "$KEY_FILE" ]]; then note "  ✓ 私钥文件存在"; else warn "  ✗ 私钥文件不存在"; MISSING=1; fi
if grep -q "BEGIN PGP PRIVATE KEY BLOCK" "$KEY_FILE" 2>/dev/null; then
  note "  ✓ 私钥格式正确（ASCII armored）"
else
  warn "  ✗ 私钥文件内容不像 ASCII armored 私钥"; MISSING=1
fi

# 真签一次：把导出的私钥导入临时钥匙串并用口令签名。
# 这样能在发布前就发现“口令不对 / 私钥文件损坏”，而不是等 ./gradlew publish 才炸。
note ""
say "自检 2：用导出的私钥试签一个文件（验证私钥可用、口令正确）"
TEST_HOME=$(mktemp -d); chmod 700 "$TEST_HOME"
if GNUPGHOME="$TEST_HOME" gpg --batch --quiet --import "$KEY_FILE" 2>/dev/null; then
  printf 'kheti signing self-test\n' > "$TEST_HOME/probe.txt"
  if GNUPGHOME="$TEST_HOME" gpg --batch --quiet --pinentry-mode loopback \
       --passphrase "$SIGNING_PASSWORD" --detach-sign "$TEST_HOME/probe.txt" 2>/dev/null; then
    note "  ✓ 私钥可导入、口令正确、签名成功"
  else
    warn "  ✗ 用该口令签名失败 —— 口令很可能不对"; MISSING=1
  fi
else
  warn "  ✗ 私钥文件无法导入临时钥匙串"; MISSING=1
fi
rm -rf "$TEST_HOME"
note ""
if (( MISSING )); then
  warn "有项目未就绪，请按上面的提示处理后重跑本脚本（已写入的值会保留）。"
else
  say "全部就绪。接下来发布（记得先递增 gradle.properties 里的 kheti.version）："
  step "./gradlew publish"
  note "上传后还需从同一 IP 调一次 Portal 接口，部署才会出现在 Portal 上；"
  note "该接口用 Bearer 认证（base64 的 token用户名:token密码），不是 Basic 认证。"
  note "完整命令与原因见 docs/publishing.md 第 3.1 节。"
fi
pause "按 Enter 结束…"

finish
